### ISSUE TITLE
rubyzip 1.3.0

### ISSUE THREAD

**Issue by klyonrad** [depfu/depfu#39]
Depfu marks the version 1.3.0 as insecure, but if I am reading [the changelog](https://github.com/rubyzip/rubyzip/blob/v2.0.0/Changelog.md#130-2019-09-25) of it correctly, it seems that version 1.3.0 is still okay.

Is the error on your side or on my understanding?

Screenshot

![image](https://user-images.githubusercontent.com/1453955/67308127-e6ef7e80-f4f9-11e9-94f2-d80deb6eb017.png)

**Comment by theflow** [comment]
Hi @klyonrad, yes, 1.3.0 is ok. That's a bug on our side where we don't detect that you manually updated to 1.3.0. I'll look into it.
