### ISSUE TITLE
Suggest replacements for abandoned gems

### ISSUE THREAD

**Issue by leoarnold** [depfu/depfu#42]
Depfu ran into a conflict trying to apply the security upgrade to Rails `6.0.3.1`. By mere fluke I found out that the aged `axlsx 3.0.0.pre` has a newer drop-in replacement called `caxlsx`.

Would be nice if Depfu could point that out so projects don't rely on abandoned gems for too long.

**Comment by halfbyte** [comment]
@leoarnold That's a great suggestion, Leo. I'll see what that would entail.

**Comment by theflow** [comment]
Closing older issues
