### ISSUE TITLE
"Next pull request" in the past (bug?)

### ISSUE THREAD

**Issue by AlexWayfer** [depfu/depfu#47]
Hello.

I see such information:

![image](https://user-images.githubusercontent.com/6510020/94680720-e6c34a00-032a-11eb-86c7-aeeeab804523.png)

I don't understand how "Next pull request" can be in the past (August, there is September now).

**Comment by theflow** [comment]
Closing older issues

**Comment by AlexWayfer** [comment]
> Closing older issues

It's still the issue:

![image](https://user-images.githubusercontent.com/6510020/179960363-74ab546c-2334-44bd-978b-74d24be22add.png)


https://depfu.com/repos/github/AlexWayfer/alexwayfer.name

I don't appreciate closing issues due to age without any resolving or even simple check.

**Comment by theflow** [comment]
you're right, it's fixed now
