### ISSUE TITLE
Login page distorted when Typekit is blocked

### ISSUE THREAD

**Issue by leoarnold** [depfu/depfu#49]
Some browser / plugins consider Adobe Typekit a tracker and block the resource. Depfu works perfectly fine without it. You just get this visual glitch:

![Screenshot_20201028_101748](https://user-images.githubusercontent.com/4201235/97416607-eeb0e280-1906-11eb-9229-1e1ef8b2eed4.png)

**Comment by theflow** [comment]
Closing older issues
