### ISSUE TITLE
Bad Repo link

### ISSUE THREAD

**Issue by leoarnold** [depfu/depfu#52]
![Screenshot_20210120_182137](https://user-images.githubusercontent.com/4201235/105211384-785dfe00-5b4c-11eb-94b6-91c8fa7bfc2b.png)

The "Repo" link points to `https://www.ruby-Rang.org/` which maybe was meant to be `https://www.ruby-Lang.org/` but probably should be `https://github.com/ruby/ruby2_keywords`

**Comment by theflow** [comment]
Thanks Leo, it's fixed now.
