### ISSUE TITLE
Can't login after changing Github username

### ISSUE THREAD

**Issue by alex-kim-dev** [depfu/depfu#55]
Getting "This page isn't working" & `ERR_TOO_MANY_REDIRECTS` in Brave. This is what happens in the network panel:

<details><summary>Network screenshot</summary>

![10](https://user-images.githubusercontent.com/45559664/135642147-958d6812-a0d0-4b53-bd27-1b8ed293f0cb.png)
</details>

[Exported `.har` data](https://pastebin.com/4HBBtfKT)

**Comment by theflow** [comment]
Hi @alex-kim-dev,

Sorry about that, looks like some webhooks got lost. I've manually triggered the sync now, can you try again if it works?


Cheers,
Florian

**Comment by alex-kim-dev** [comment]
Works now, thanks Florian! :clap:
