### ISSUE TITLE
(npm private repo fails) Depfu cannot access this registry.

### ISSUE THREAD

**Issue by dcfranca** [depfu/depfu#56]
I'm trying to update `depfu` with the new npm token format: https://github.blog/2021-09-23-announcing-npms-new-access-token-format/

I have generated a new token type `Automation`, which should work with CI/CD pipelines
However, depfu keeps giving this error message on the configuration page:

> Depfu cannot access this registry. Everything will continue to work but we won't send you PRs for any of the packages hosted here.

The detection seems to have worked fine and it shows on the `Organization Settings` page:

> @mycompany on https://registry.npmjs.org/ 

But the error message is still there on the `Organization Settings` page.

I also have tried generating other types of tokens (`Readonly` and `Publish`), but they don't seem to be correct and don't work either.

I even tried using `username:password` as stated here: https://docs.depfu.com/article/31-private-package-registries
Still same error

The error message doesn't give more specific details about why it is failing

Any idea what could be happening? Or how can I debug this issue better?

**Comment by halfbyte** [comment]
This has been debugged with @dcfranca and we've found the issue - It has nothing to do with the new token format which should work exactly as the old token format has.
