### ISSUE TITLE
BulmaJS: no changelog

### ISSUE THREAD

**Issue by noraj** [depfu/depfu#58]
![image](https://user-images.githubusercontent.com/16578570/175831665-47e8b71e-06e4-4f76-aea5-6354e9547e6f.png)

There is not changelog file but there is a changelog on github release https://github.com/VizuaaLOG/BulmaJS/releases/tag/0.12.2

**Comment by theflow** [comment]
@noraj thanks for letting us know. Somehow this wasn't detected, but I've fixed it now
