### ISSUE TITLE
How does Depfu count?

### ISSUE THREAD

**Issue by leoarnold** [depfu/depfu#59]
I count 2 open PRs and 13 queued. How does Depfu arrive at 3 and 15?

![Screenshot_2022-07-14_22-18-43](https://user-images.githubusercontent.com/4201235/179076100-cd639929-a5b8-45b5-a052-c35ccf595573.png)

**Comment by theflow** [comment]
@leoarnold We haven't built this very resilient, to be honest. Sometimes webhooks from GitHub don't arrive and then the count gets off. If you tell me which repo, I can look into the exact issue and see if I can find a fix.

**Comment by leoarnold** [comment]
Let's just call it "eventual consistency" then :wink:
