### ISSUE TITLE
Depfu shows an incorrect repository link for `open`.

### ISSUE THREAD

**Issue by canova** [depfu/depfu#65]
[Here in this PR](https://github.com/firefox-devtools/profiler/pull/4561), depfu updated the `open` development dependency.

It shows this repository: https://github.com/pwnall/node-open
But actually it should be: https://github.com/sindresorhus/open

Its npm page: https://www.npmjs.com/package/open

Of course, because of this, it also can't show changelog or diff. I don't know what's happening there but I can't find a published npm package for the incorrect repo.

**Comment by halfbyte** [comment]
Thanks for reporting this. odd error. I've corrected it.
